services:
  jenkins-master:
    build:
      context: ../ApiForJenkin
      dockerfile: jenkins-master.dockerfile
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  api-agent:
    build:
      context: ../ApiForJenkin
      dockerfile: api-agent.dockerfile
    container_name: jenkins-api-agent
    network_mode: "container:jenkins-master"
    environment:
      - JENKINS_SECRET=jenkins_secret_for_api_agent
      - AGENT_NAME=api-agent
      - MAVEN_OPTS=-Dtest.db.environment=jenkins
    command: ["/home/jenkins/start-agent.sh"]
    volumes:
      - api_workspace:/home/jenkins/agent
      - ./start-agent.sh:/home/jenkins/start-agent.sh:ro
    depends_on:
      - jenkins-master
    restart: unless-stopped

  ui-agent:
    build:
      context: ../ApiForJenkin
      dockerfile: ui-agent.dockerfile
    container_name: jenkins-ui-agent
    network_mode: "container:jenkins-master"
    environment:
      - JENKINS_SECRET=jenkins_secret_for_ui_agent
      - AGENT_NAME=ui-agent
    command: ["/home/jenkins/start-agent.sh"]
    volumes:
      - ui_workspace:/home/jenkins/agent
      - /dev/shm:/dev/shm
      - ./start-agent.sh:/home/jenkins/start-agent.sh:ro
    shm_size: 2g
    depends_on:
      - jenkins-master
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0
    container_name: mysql-test-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpass
      DOCKER_INFLUXDB_INIT_ORG: test-org
      DOCKER_INFLUXDB_INIT_BUCKET: test-results
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-auth-token
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - influxdb
    restart: unless-stopped

  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: unless-stopped

  selenium-chrome:
    image: selenium/node-chrome:4.15.0
    container_name: selenium-chrome
    ports:
      - "7900:7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSIONS=3
    shm_size: 2gb
    depends_on:
      - selenium-hub
    restart: unless-stopped

  selenium-firefox:
    image: selenium/node-firefox:4.15.0
    container_name: selenium-firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
    shm_size: 2gb
    depends_on:
      - selenium-hub
    restart: unless-stopped

  selenium-edge:
    image: selenium/node-edge:4.15.0
    container_name: selenium-edge
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
    shm_size: 2gb
    depends_on:
      - selenium-hub
    restart: unless-stopped

volumes:
  jenkins_home:
    external: true
  api_workspace:
  ui_workspace:
  mysql_data:
  influxdb_data:
  grafana_data: