FROM jenkins/jenkins:lts-jdk21

USER root

# Устанавливаем Maven и Docker CLI
RUN apt-get update && \
    apt-get install -y maven docker.io && \
    apt-get clean

# Добавляем jenkins в группу docker
RUN groupadd -for docker && usermod -aG docker jenkins

USER jenkins
